name: ORAssistant CI
run-name: ${{ github.actor }} started CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build-backend-docker:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup prereqs
      run: make init-dev
    - name: Run formatting checks
      run: |
        make format
        make check
    - name: Populate environment variables
      run: |
        cp backend/.env.example backend/.env
        sed -i 's|{{GOOGLE_API_KEY}}|${{ secrets.GOOGLE_API_KEY }}|g' backend/.env
        sed -i 's|{{PATH_TO_GOOGLE_APPLICATION_CREDENTIALS}}|src/secret.json|g' backend/.env
        cp ${{ secrets.PATH_TO_GOOGLE_APPLICATION_CREDENTIALS }} backend/src
    - name: Build Docker image
      run: |
        make docker
    - name: Run LLM CI
      working-directory: evaluation
      run: |
        cp ../backend/.env .
        make llm-tests
    - name: Create commit comment
      uses: peter-evans/commit-comment@v3
      with:
        token: ${{ secrets.GH_PATH }}
        body-path: evaluation/auto_evaluation/llm_tests_output.txt
    - name: Teardown
      if: always()
      run: |
        docker compose down --remove-orphans
